mvt = read.csv("mvt.csv", stringsAsFactors=FALSE)
mvt$Date = strptime(mvt$Date, format="%m/%d/%y %H:%M")
str(mvt)
mvt$Weekday = weekdays(mvt$Date)
mvt$Hour = mvt$Date$hour
str(mvt)
table(mvt$Weekday)
WeekdayCounts = as.data.frame(table(mvt$Weekday))
str(WeekdayCounts)
library(ggplot2)
ggplot(WeekdayCounts, aes(x = Var1, y = Freq)) + geom_line(aes(group = 1))
WeekdayCounts$Var1 = factor(WeekdayCounts$Var1, ordered=TRUE, levels=c("Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday","Saturday"))
ggplot(WeekdayCounts, aes(x = Var1, y = Freq)) + geom_line(aes(group = 1))
ggplot(WeekdayCounts, aes(x = Var1, y = Freq)) + geom_line(aes(group = 1)) + xlab("Day of the Week") + ylab("Total Motor Vehicle Thefts")
table(mvt$Weekday, mvt$Hour)
DayHourCounts = as.data.frame(table(mvt$Weekday, mvt$Hour))
str(DayHourCounts)
DayHourCounts$Hour = as.numeric(as.character(DayHourCounts$Var2))
ggplot(DayHourCounts, aes(x = Hour, y = Freq)) + geom_line(aes(group = Var1))
ggplot(DayHourCounts, aes(x = Hour, y = Freq)) + geom_line(aes(group = Var1,colour = Var1), size = 2)
# Seperate Weekend and Weekday
DayHourCounts$Type = ifelse(DayHourCounts$Var1 == "Sunday" | DayHourCounts$Var1 == "Sarturday", "Weekend", "Weekday")
ggplot(DayHourCounts, aes(x = Hour, y = Freq)) + geom_line(aes(group = Var1,colour = Var1), size = 2)
ggplot(DayHourCounts, aes(x = Hour, y = Freq)) + geom_line(aes(group = Var1,colour = Type), size = 2, alpha = 0.5)
DayHourCounts$Var1 = factor(DayHourCounts$Var1, ordered = T, levels = c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"))
ggplot(DayHourCounts, aes(x = Hour, y = Freq)) + geom_tile(aes(fill = Freq))
ggplot(DayHourCounts, aes(x = Hour, y = Var1)) + geom_tile(aes(fill = Freq))
ggplot(DayHourCounts, aes(x = Hour, y = Var1)) + geom_tile(aes(fill = Freq)) + scale_fill_gradient(name = "Total MV Thefts", low = "Whilt", high = "Red") + theme(axis.title.y = element_blank())
# Heatmap
install.packages("maps")
install.packages("ggmap")
library(maps)
library(ggmap)
chicago = get_map(location = "chicago", zoom = 11)
ggmap(chicago)
ggmap(chicago) + geom_point(data = mvt[1:100,], aes(x = Longitude, y = Latitude))
latLonCounts = as.data.frame(table(round(mvt$Longitude,2), round(mvt$Latitude,2)))
latLonCounts$Long = as.numeric(as.character(latLonCounts$Var1))
latLonCounts$Lat = as.numeric(as.character(latLonCounts$Var2))
ggmap(chicago) + geom_point(data = latLonCounts, aes(x = Long, y = Lat, colour = Freq, size = Freq))
ggmap(chicago) + geom_point(data = latLonCounts, aes(x = Long, y = Lat, color = Freq, size=Freq)) + scale_colour_gradient(low="yellow", high="red")
ggmap(chicago) + geom_tile(data = latLonCounts, aes(x = Long, y = Lat, alpha = Freq), fill="red")
