stocks = read.csv("StocksCluster.csv")
str(stocks)
table(stocks$PositiveDec)
6324/(5256+6324)
cor(stocks)
# Logistic Regression model
library(caTools)
set.seed(144)
split = sample.split(stocks, SplitRatio = 0.7)
train = subset(stocks, split == T)
test = subset(stocks, split == F)
modelLog = glm(PositiveDec ~., data = train, family = binomial)
summary(modelLog)
pred = predict(modelLog, newdata = test, type = "response")
table(test$PositiveDec, pred > 0.5)
(477+1719)/(477+1282+382+1719)
table(test$PositiveDec)
2101/(1759+2101)
# Cluster method
limitedTrain = train
limitedTrain$PositiveDec = NULL
limitedTest = test
limitedTest$PositiveDec = NULL
library(caret)
preproc = preProcess(limitedTrain)
normTrain = predict(preproc, limitedTrain)
normTest = predict(preproc, limitedTest)
summary(normTrain)
mean(normTrain$ReturnJan)
# K-means
set.seed(144)
km = kmeans(normTrain, centers = 3)
table(km$cluster)
install.packages("flexclust")
library(flexclust)
km.kcca = as.kcca(km, normTrain)
clusterTrain = predict(km.kcca)
clusterTest = predict(km.kcca, newdata = normTest)
table(clusterTest)
# Cluster specific predictions
stockTrain1 = subset(train, clusterTrain ==1)
stockTrain2 = subset(train, clusterTrain ==2)
stockTrain3 = subset(train, clusterTrain ==3)
stockTest1 = subset(test, clusterTest ==1)
stockTest2 = subset(test, clusterTest ==2)
stockTest3 = subset(test, clusterTest ==3)
mean(stockTrain1$PositiveDec)
mean(stockTrain2$PositiveDec)
mean(stockTrain3$PositiveDec)
# Build logistic regression of each cluster
stockModel1 = glm(PositiveDec ~., data = stockTrain1, family = binomial)
stockModel2 = glm(PositiveDec ~., data = stockTrain2, family = binomial)
stockModel3 = glm(PositiveDec ~., data = stockTrain3, family = binomial)
predModel1 = predict(stockModel1, newdata = stockTest1, type = "response")
predModel2 = predict(stockModel2, newdata = stockTest2, type = "response")
predModel3 = predict(stockModel3, newdata = stockTest3, type = "response")
table(stockTest1$PositiveDec, predModel1 > 0.5)
(49+656)/(49+656+46+396)
# ACC1 = 0.61
table(stockTest2$PositiveDec, predModel2 > 0.5)
(323+893)/(323+893+754+263)
# ACC2 = 0.54
table(stockTest3$PositiveDec, predModel3 > 0.5)
(139+149)/(139+149+98+94)
# ACC3 = 0.6
AllPredictions = c(predModel1, predModel2, predModel3)
AllOutcomes = c(stockTest1$PositiveDec, stockTest2$PositiveDec, stockTest3$PositiveDec)
table(AllOutcomes, AllPredictions > 0.5)
(511+1698)/(511+1248+1698+403)
